### ISSUE TITLE
NOT_DEFINED_CATEGORY

### ISSUE THREAD

**Issue by hfmartinez85** [iaw-2022/FerminAlvarez-js#3]
Hola Fermín,

Te muestro un detalle, que si lo podés corregir en la entrega de la conexión con la API estaría buenísimo: fijate que cuando no tiene categoría le muestra un mensaje muy técnico y en inglés al usuario, tal vez sea mejor mostrar "--" o simplemente no mostrar nada

![image](https://user-images.githubusercontent.com/50154762/172723955-6e55c64f-36b0-4736-950c-09ecf77cd4ac.png)

**Comment by FerminAlvarez** [comment]
Ahí está corregido.
